models:
  - name: int_pagos_por_pedido
    description: "Intermediate model for pagos por pedido"
    columns:
      - name: pedido_id
        description: "ID of the pedido"
      - name: importe
        description: "Suma de los pagos de cada pedido"
    config:
      materialized: ephemeral